- code/Home.py
- code/streamlit_util.py
> x quantiles for mean plot

- code/Home.py
- code/streamlit_util.py
> fix regex caching

- code/Home.py
- code/pages/1_Old mice.py
- code/util/streamlit.py
> Queryable urls

- code/util/streamlit.py
A bug presumably caused by a Streamlit internal bug with st.experimental_rerun()?
- resolves #28
> Fix the bug of the main page when clicking on sessions in the table

- code/Home.py
- code/util/streamlit.py
> Han improve curriculum selector

- code/pages/1_Old mice.py
- code/pages/2_Population analysis.py
Reverts AllenNeuralDynamics/foraging-behavior-browser#41
> Revert "Han shut down streamlit cloud"

- code/Home.py
Added logistic regression plots from four models
- resolves #45
> feat: add logistic regression fits

- code/Home.py
- code/pages/3_PyGWalker.py
- gw_config.json
- requirements.txt
- resolves #47 
The user can export any plot setting to json
and then reproduce the plots
> feat: add pywalker

- code/Home.py
- code/pages/1_Old mice.py
- code/util/streamlit.py
- gw_config_old_mice.json
- requirements.txt
- resolves #37 
- resolves #27
> feat: increase the length of x-y selector fields

- code/Home.py
> fix: issue 51

- code/Home.py
- code/util/streamlit.py
- gw_config.json
> feat: minor tweaks for the foraging meeting

- code/Home.py
- code/util/streamlit.py
Finally, all old bpod sessions can share the same downstream analysis!
- resolves #56
> feat: integrate bpod sessions

- code/pages/3_Playground.py
- environment/Dockerfile
- requirements.txt
- Still WIP. Merge for demo purpose.
> feat: dim reduction

- code/Home.py
- code/util/aws_s3.py
- code/util/plot_autotrain_manager.py
- code/util/streamlit.py
> feat: add quick preview to the autotrain manager

- code/Home.py
- code/util/streamlit.py
> Fix: collapsing slider range when only one sessions is filtered

- code/pages/2_HMM-GLM.py
- Add data explorer for Faeze's HMM-GLM models
> feat: add HMM-GLM for Faeze

- code/pages/2_HMM-GLM.py
- some bugs and minor improvements
> fix: some bugs in HMM-GLM

- code/pages/2_HMM-GLM.py
- Improved group_by_states: allow user to select which states to compare
> feat: bug fix and improve grouped_by_states

- code/Home.py
- code/util/settings.py
- Add Sue's lick analysis plot
> feat: add Sue's lick analysis plot

- code/Home.py
- code/util/aws_s3.py
> feat: add pipeline-rerun message

- code/pages/3_AIND data access playground.py
- code/util/fetch_data_docDB.py
- requirements.txt
- A simple demo of accessing docDB
- Will be working on comparing it with my pipeline once it recovers.
> feat: put David's app in

- code/Home.py
- code/pages/3_AIND data access playground.py
- reorder the columns so that AutoTrain info is easier to see
- fix #68
> Han minor improvements

- code/Home.py
- code/util/aws_s3.py
- code/util/plot_autotrain_manager.py
- code/util/settings.py
- code/util/streamlit.py
- code/util/url_query_helper.py
- environment/Dockerfile
- environment/postInstall
Some improvements on AutoTrain visualization
- make autotrain the default tab
- improve hover label
- improve sorting
> feat: Han improve autotrain

- code/util/plot_autotrain_manager.py
- code/util/streamlit.py
- code/util/url_query_helper.py
> Han fix plotly selection

- .streamlit/config.toml
- code/Home.py
- code/pages/3_AIND data access playground.py
- code/util/fetch_data_docDB.py
- code/util/streamlit.py
- environment/Dockerfile
- requirements.txt
Left join the master table from Han's pipeline with the dataframe get from docDB. Here are columns added
The users can now leverage the existing functions of the app to filter with new columns from docDB.
166 out of 3452 sessions (15 out of 155 mice) are filtered
Then you can export the filtered df as CSV by pressing the recently added button.
@alexpiet
> feat: Merge in dataframe from docDB

- code/Home.py
- environment/postInstall
- Add a new column `docDB_stataus` for convenience
> feat: add doc db status

- code/Home.py
- gw_config.json
- Now we can track data uploading status more easily: in the streamlit app, click "PyGWalker" Tab -> choose "Check docDB status" page:
> feat: add doc db status to pygwalker

- code/util/fetch_data_docDB.py
in my last PR, i somehow lost the lines for the code ocean data asset ID's. doing a PR now so that we can add that back in.
> Adding nlight for recognizing NM and also re-adding the code ocean data asset ID's

- code/Home.py
- code/util/fetch_data_docDB.py
1. cleared up the external links (have unprocessed/processed versions and naming them clearly) 
2. took out intended NM 
4. took out dupe entries (no longer a problem)
> cleaning up some data pulled from mongoDB 

- code/pages/1_Learning trajectory.py
> fix trajectory page

- code/Home.py
- code/pages/1_Basic behavior analysis.py
- code/util/plot_autotrain_manager.py
- code/util/streamlit.py
- code/util/url_query_helper.py
> Han #105 performance improvements

- code/Home.py
- code/pages/0_Data inventory.py
- code/pages/1_Basic behavior analysis.py
- code/util/aws_s3.py
- code/util/foraging_plotly.py
- code/util/plot_autotrain_manager.py
- code/util/settings.py
- code/util/streamlit.py
- code/util/url_query_helper.py
- requirements.txt
- Upgrade Streamlit to the latest version 1.41.0
- Use the new st.fragment to greatly improve performance
- Use the new st.plotly_chart that natively supports call back events (and remove streamlit-plotly-events)
- Use orjson to improve plotly loading speed
- Other minor bug fixes
> Streamlit 1.41 upgrade and performance enhancements

- code/Home.py
- code/pages/0_Data inventory.py
- Merge in PI names
- Use aggrid to show dfs
- Other minor improvements
> Merge in PI name to data inventory

- code/Home.py
- code/pages/0_Data inventory.py
- code/util/aws_s3.py
- code/util/plot_autotrain_manager.py
- code/util/streamlit.py
- environment/Dockerfile
- environment/postInstall
1. Fixed a bug caused by recent adding of non-normzlied curriculum and stage names from the new curriculum system
2. Get curriculum info from result-access-api (autotrain). See https://github.com/AllenNeuralDynamics/aind-analysis-arch-result-access/pull/17
3. Multiple minor improvements.
> Multiple Improvements on autotrain
